import { Sample, SampleStatus } from '@/types';

/** API 미연결 시 미리보기용 샘플 데이터 (스크린샷과 유사) */
export const PREVIEW_SAMPLES: Sample[] = [
  {
    id: 9001,
    regDate: '2025-03-10',
    status: '대여가능',
    brand: '중국포인포',
    locationNo: '-',
    code: 'PCCAI032991',
    name: '2025 코튼 트렌치 코트 (출장샘플)',
    category: '오리지널',
    registerer: '허경아',
    useYn: '사용',
    color: '핑크',
    gender: '여성',
    country: '일본',
    price: 25000,
    description: '일본 출장에서 수집한 코튼 트렌치 코트 샘플입니다.',
    brandCode: 'CN',
    season: 'FW',
    material: '면 100%',
    size: 'M',
    condition: '아주 좋음',
    rentalFee: 25000,
    rentalPeriod: 28,
    aiTags: { design: ['trench', 'belted'], style: ['minimal'], color: ['pink'], season: ['fall'] },
  },
  {
    id: 9002,
    regDate: '2025-02-20',
    status: '대여중',
    brand: 'ZARA',
    locationNo: '-',
    code: 'PCCAI032990',
    name: '25SS 캐주얼 오버롤 팬츠',
    category: '촬영샘플',
    registerer: '김지훈',
    useYn: '사용',
    color: '베이지',
    gender: '공용',
    country: '한국',
    price: 18000,
    description: '촬영 레퍼런스용 오버롤 팬츠',
    brandCode: 'KR',
    season: 'SS',
    material: '면 혼방',
    rentalFee: 18000,
  },
  {
    id: 9003,
    regDate: '2025-01-15',
    status: '연체중',
    brand: '중국포인포',
    locationNo: '-',
    code: 'PCCAI032989',
    name: '나일론 윈드브레이커',
    category: 'EP샘플',
    registerer: '박아름',
    useYn: '사용',
    color: '블랙',
    gender: '남성',
    country: '중국',
    price: 22000,
    description: 'EP 라인 윈드브레이커',
    brandCode: 'CN',
    season: 'SS',
    material: '나일론',
    rentalFee: 22000,
  },
  {
    id: 9004,
    regDate: '2024-12-01',
    status: '부평보관',
    brand: '스파오',
    locationNo: '-',
    code: 'PCCAI032988',
    name: '램스울 라운드 가디건',
    category: '오리지널',
    registerer: '이도헌',
    useYn: '사용',
    color: '그레이',
    gender: '여성',
    country: '한국',
    price: 15000,
    description: '부평 보관 중인 가디건',
    brandCode: 'KR',
    season: 'FW',
    material: '램스울',
    rentalFee: 15000,
  },
  {
    id: 9005,
    regDate: '2024-11-20',
    status: '분실',
    brand: '후아유',
    locationNo: '-',
    code: 'PCCAI032987',
    name: '셔츠 카라 미니 원피스',
    category: '촬영샘플',
    registerer: '최민서',
    useYn: '사용',
    color: '화이트',
    gender: '여성',
    country: '한국',
    price: 20000,
    description: '분실 처리된 샘플',
    brandCode: 'KR',
    season: 'SS',
    material: '면',
    rentalFee: 20000,
  },
  ...Array.from({ length: 8 }, (_, i) => ({
    id: 9010 + i,
    regDate: '2025-03-01',
    status: (i % 3 === 0 ? '대여가능' : i % 3 === 1 ? '대여중' : '연체중') as SampleStatus,
    brand: ['ZARA', '중국포인포', '스파오'][i % 3],
    locationNo: '-',
    code: `PCCAI0329${80 - i}`,
    name: ['데일리 하이넥 바람막이', '프렌치 자카드 재킷', '유선형 스트라이프 원피스', 'EP 프리미엄 가디건'][i % 4],
    category: ['오리지널', '촬영샘플', 'EP샘플'][i % 3],
    registerer: '허경아',
    useYn: '사용' as const,
    color: '네이비',
    gender: '공용',
    country: '한국',
    price: 16000 + i * 500,
    description: '미리보기 샘플',
    brandCode: 'KR',
    season: 'FW',
    material: '폴리에스터',
    rentalFee: 16000,
  })),
];

export const PREVIEW_MEMBERS = [
  {
    memberId: '20240112',
    name: '허경아',
    email: 'her_kyoungar@eland.co.kr',
    phone: '010-4491-9982',
    groupName: '패션BG 본부',
    affiliation: '패션BG 본부',
    brand: '패션연구소',
    useYn: '사용' as const,
    loginId: 'her_kyoungar',
  },
];

export const PREVIEW_RENTALS = [
  {
    rentalId: '1634001',
    sampleCode: 'PCCAI032990',
    sampleName: '25SS 캐주얼 오버롤 팬츠',
    sampleBrand: 'ZARA',
    borrowerId: '20240112',
    borrowerName: '허경아',
    borrowerEmail: 'her_kyoungar@eland.co.kr',
    borrowerGroup: '패션BG 본부',
    rentDate: '2025-05-20',
    dueDate: '2025-06-17',
    returnDate: null,
    status: '대여중' as const,
    notifyCount: 0,
    lastNotifyDate: null,
    notifyHistory: [],
  },
  {
    rentalId: '1634002',
    sampleCode: 'PCCAI032989',
    sampleName: '나일론 윈드브레이커',
    sampleBrand: '중국포인포',
    borrowerId: '20240112',
    borrowerName: '허경아',
    borrowerEmail: 'her_kyoungar@eland.co.kr',
    borrowerGroup: '패션BG 본부',
    rentDate: '2025-04-01',
    dueDate: '2025-04-29',
    returnDate: null,
    status: '연체중' as const,
    notifyCount: 1,
    lastNotifyDate: '2025-05-10',
    notifyHistory: [],
  },
];
